apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: faas-idler
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faas-idler
    spec:
      containers:
      - name: faas-idler
        image: openfaas/faas-idler:0.1.9
        imagePullPolicy: Always
        env:
          - name: gateway_url
            value: "http://127.0.0.1:31112/"
          - name: prometheus_host
            value: "10.43.233.209"
          - name: prometheus_port
            value: "9090"
          - name: inactivity_duration
            value: "5m"
          - name: reconcile_interval
            value: "30s"
        command:
          - /home/app/faas-idler
          - -dry-run=true
        volumeMounts:
        - name: auth
          readOnly: true
          mountPath: "/var/secrets/"
      volumes:
      - name: auth
        secret:
          secretName: basic-auth
